from weakref import WeakKeyDictionary


class Event:
    """A superclass for any events that might be generated by an
    object and sent to the EventManager.
    """

    def __repr__(self):
        return f"{self.__class__.__name__}()"


class QuitEvent(Event):
    pass


class TickEvent(Event):
    pass


class InputEvent(Event):  # todo split to Keyboard and MouseClick Event
    """Keyboard or mouse input event"""

    def __init__(self, unicode_char, click_pos):
        self.char = unicode_char
        self.click_pos = click_pos

    def __repr__(self):
        return f'{self.__class__.__name__}(unicode_char="{self.char}", click_pos={self.click_pos})'


class InitializeEvent(Event):
    """Tells all listeners to initialize themselves.
    This includes loading libraries and resources.

    Avoid initializing such things within listener __init__ calls
    to minimize snafus todo ???
    (if some rely on others being yet created)
    """

    pass


class StateChangeEvent(Event):
    """Change the model state machine.
    Given a None state will pop() instead of push
    """

    def __init__(self, state):
        self.state = state

    def __str__(self):
        if self.state:
            return f"{self.__class__.__name__} pushed {self.state}"
        else:
            return f"{self.__class__.__name__} popped"


class EventManager:
    """
    Coordinates the communication between the Model, View and Controller
    """

    def __init__(self):
        self.listeners = WeakKeyDictionary()

    def register_listener(self, listener):
        """Adds a listener to our spam list
        It will receive Post()ed events through its notify(event) call
        """

        self.listeners[listener] = 1

    def unregister_listener(self, listener):
        """Remove a listener from our spam list.
        This is implemented byt hardly used.
        Our weak ref spam list will auto remove any listener who stops existing
        """
        if listener in self.listeners.keys():
            del self.listeners[listener]

    def post(self, event):
        if not isinstance(event, TickEvent):
            # print the event (unless it is TickEvent)
            print(str(event))

        for listener in self.listeners:
            listener.notify(event)


class Listener:
    """Base Listener class. Implements registering listeners and
    an abstract method for notify()ing subscribers.
    """

    def __init__(self, event_manager: EventManager):
        self.event_manager = event_manager
        event_manager.register_listener(self)

    def notify(self, event):
        raise NotImplementedError
